---
- name: Update packages
  become: true
  apt:
    upgrade: no
    update_cache: yes
  
- name: Install apt repos
  become: true
  apt:
    name: "{{repos}}"
  vars:
    repos:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - software-properties-common

- name: Download Docker repo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: add-apt-repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    #state: stable

- name: Update packages
  become: true
  apt:
    upgrade: no
    update_cache: yes

- name: Install Docker
  become: true
  apt:
    name: "{{repos}}"
  vars:
    repos:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: usermod to Docker
  become: true
  command: usermod -aG docker ubuntu

# - name: usermod to jenkins
#   become: true
#   command: usermod -aG docker jenkins
#   when: 
#     - "'Bastion' in groups"